# Generated by Django 3.2.14 on 2022-07-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='total_remaining_amt',
            field=models.IntegerField(default=0),
        ),
    ]
