# Generated by Django 3.2.14 on 2022-09-03 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_income_total_remaining_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.date(2022, 9, 3), verbose_name='income_date'),
        ),
        migrations.AddField(
            model_name='income',
            name='time',
            field=models.TimeField(default=datetime.time(20, 22, 50, 451504), verbose_name='income_time'),
        ),
    ]
