# Generated by Django 3.2.14 on 2022-09-10 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20220903_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.date(2022, 9, 10), verbose_name='income_date'),
        ),
        migrations.AlterField(
            model_name='income',
            name='time',
            field=models.TimeField(default=datetime.time(17, 30, 43, 697135), verbose_name='income_time'),
        ),
    ]
